CREATE TABLE url (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code VARCHAR(16) UNIQUE,
    long_url   VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP     NOT NULL DEFAULT now(),
    expires_at TIMESTAMP,
    owner_id   INTEGER
);
